### DISCUSSION TITLE
Is it possible to re-use help text?

### DISCUSSION THREAD

**Discussion by b-long** [nat-n/poethepoet#116] [Q&A]
In a scenario where I'm writing several tasks that have the same very long/verbose help text, it'd be useful to reuse that help text.  For instance, imagine one task:

```toml
[tool.poe.tasks.do_the_foo]
shell = "do_foo"
help = "Do a thing."

    [[tool.poe.tasks.do_the_foo.args]]
    name = "bar"
    help = """
    The input file (.ini or .yml) to evaluate.

    The default input file is 'resources/default_bar.yml'.  Pass another
    input file using the flag -b, --bar.

    Example: 
        poetry run poe do_the_foo -b resources/other.ini
    """
    default = "resources/default_bar.yml"
    options = [ "-b", "--bar" ]
```

Now, if I want to declare 3 more tasks that take a `--bar` input file, and I want to provide the same verbose help, the file starts to grow very quickly.

Is there some mechanism to re-use help text?

**Comment by nat-n** [comment]
Hi @b-long, 

I'm afraid there's no support for anything like this today. Off the top of my head I can't think of a very elegant way to implement sharing of help text specifically. Though I wonder if what you really want is to reuse entire arg definitions? That's a feature I could imagine being more broadly useful.

Perhaps like so?

```toml
[[tool.poe.reusable_args]]
name = "bar"
help = """
The input file (.ini or .yml) to evaluate.

The default input file is 'resources/default_bar.yml'.  Pass another
input file using the flag -b, --bar.

Example: 
    poetry run poe do_the_foo -b resources/other.ini
"""
default = "resources/default_bar.yml"
options = [ "-b", "--bar" ]

[tool.poe.tasks.do_the_foo]
shell = "do_foo"
help  = "Do a thing."
args  = [{ reuse = "bar" }]
```
