### DISCUSSION TITLE
How to derive a task from another and add additional arguments to it?

### DISCUSSION THREAD

**Discussion by johhnry** [nat-n/poethepoet#130] [Q&A] [answered]
Hi,

First of all, great project!

I would like to have two different tasks:

- `ruff check .` (only lint check)
- `ruff check . --fix` (lint and fix)

Is there a better way to define those two tasks without having to do this?

```toml
[tool.poe.tasks]
lint-check = { cmd = "ruff check .", help = "Lint code" }
lint-fix = { cmd = "ruff check . --fix", help = "Lint code and fix" }
```

Like extending a previous task:

```toml
lint-check = { cmd = "ruff check .", help = "Lint code" }
lint-fix = { extends = "lint-check", args = ["--fix"], help = "Lint code and fix" }
```

Thanks!

**Comment by nat-n** [comment, marked as answer]
Hi @johhnry, thanks for the feedback :)

Personally I think that level of repetition between tasks is fine, but I'll humour the question.

There's no explicit inheritance mechanism for poe tasks, but you can get some degree of reuse with a [ref task](https://github.com/nat-n/poethepoet#ref-tasks).

Firstly, your question made me realise ref tasks don't behave exactly as I had in mind, so I made [this change](https://github.com/nat-n/poethepoet/commit/383b19fd87047fc78780cb4746b1df2887173fef#diff-8a9c129d41eddeeea059d69986d984f8df38c6e85201c04aa9f6862cb423dc28) which will be include in the 0.19.0 release soon. With that you'll be able to achieve what you want with the following:

```toml
[tool.poe.tasks]
lint-check = { cmd = "ruff check .", help = "Lint code" }
lint-fix   = { ref = "lint-check --fix", help = "Lint code and fix" }
```
