### DISCUSSION TITLE
Can't use  os.path.isdir in case

### DISCUSSION THREAD

**Discussion by mgzenitech** [nat-n/poethepoet#135] [Q&A] [answered]
```toml
[tool.poe.tasks.post_install]
control.script = "os.path:isdir('.venv/node')"

[[tool.poe.tasks.post_install.switch]]
case = "False"
sequence = [
  ...
]

[tool.poe.poetry_hooks]
post_install = "post_install"
```

Is always getting me:
Error: Control value '' did not match any cases in switch task 'post_install'. 
Cancelling command due to failed hook task

**Comment by mgzenitech** [comment]
Any ideas on how to check for existing directory with script?

**Comment by nat-n** [comment, marked as answer]
Hi @mgzenitech,

You can make your example work by configuring the control script task to [print the result](https://github.com/nat-n/poethepoet#output-the-return-value-from-the-python-callable). The problem is that cases are compared to the output of the script task, and although the isdir function returns a boolean value is doesn't output (i.e. print) anything.

```toml
[tool.poe.tasks.post_install]
control.script       = "os.path:isdir('.venv/node')"
control.print_result = true

...
```

However I would usually recommend using an `expr` task in a situation like this:

```toml
[tool.poe.tasks.post_install]
control.expr    = "os.path.isdir('.venv/node')"
control.imports = ["os"]

...
```
