### DISCUSSION TITLE
How would someone put multiline "script" in switch?

### DISCUSSION THREAD

**Discussion by mgzenitech** [nat-n/poethepoet#138] [Q&A] [answered]
Right now, I have this nasty expression:
```python
control.expr = """
pathlib.Path(".venv/bin/npm").is_file() and set(
  pathlib.Path("node-requirements.txt").read_text().split("\\n")[0:-1]).intersection(set(
    re.findall(r"[a-z-]+@(?:[0-9]+\\.?)+", subprocess.run(["npm", "ls", "-g"], capture_output = True) \
      .stdout.decode("utf-8")
  ))
)
"""
control.imports = ["re", "subprocess", "pathlib"]
```

Is it possible to write multi statement "script" (something using variables, exception handling, etc)?

**Comment by nat-n** [comment]
The point of the [expr](https://github.com/nat-n/poethepoet#expr-tasks) task is to streamline the use-case where you want to evaluate a single python expression.

For the most powerful option would be to use a [script](https://github.com/nat-n/poethepoet#script-tasks) task to call a python function defined somewhere in your project (I usually put stuff in src/tasks.py, which doesn't have to be included in the build).

In general you can define a [shell](https://github.com/nat-n/poethepoet#shell-tasks) with `interpreter = "python"` to just embed a python script, but unfortunately switch control tasks cannot be shell tasks (can't remember exactly why just that it complicated things a bunch).

**Reply by mgzenitech** [reply]
@nat-n how would I access then the arguments? I've tried just plain variables, but it didn't work:
```toml
[tool.poe.tasks.build]
shell = """
  print(path)
"""
interpreter = "python"

[[tool.poe.tasks.build.args]]
name = "path"
positional = true
help = "Path to the Dockerfile"
required = true
```

```sh
poetry poe build base/Dockerfile
```

```
NameError: name 'path' is not defined. Did you mean: 'Path'?
```

**Reply by nat-n** [reply, marked as answer]
Accessing arguments as python variables only works for `script` or `expr` tasks, but shell tasks using python as an interpreter aren't as clever because they work by passing a whole script to the python interpreter, rather than composing one dynamically from the given components.

For shell tasks you can access the arg value as an environment variable like so:

```toml
[tool.poe.tasks.build]
shell = """
  from os import environ
  print(environ.get("DF_PATH"))
"""
interpreter = "python"

  [[tool.poe.tasks.build.args]]
  name       = "DF_PATH"
  options    = ["--path", "-p"]
  positional = true
  default    = "./Dockerfile"
  help       = "Path to the Dockerfile"
```

Notice I avoided calling the variable `path` since it's going via the environment.

> N.B. shell tasks cannot be used for the control task in a switch statement, see previous answer.
