### DISCUSSION TITLE
How to pass boolean argument downstream to subtask?

### DISCUSSION THREAD

**Discussion by mgzenitech** [nat-n/poethepoet#143] [Q&A]
```toml
[tool.poe.tasks.build]
sequence = [
  "_build",
  "_squash ${HOW TO PASS NON POSITIONAL BOOLEAN ARGUMENT HERE???}"
]

[[tool.poe.tasks.build.args]]
name = "compress"
options = ["--compress", "-c"]
help = "Compress the layers?"
type = "boolean"
default = false

[tool.poe.tasks._build]
...

[tool.poe.tasks._squash]
control.expr = "compress"
default = "pass"

[[tool.poe.tasks._squash.switch]]
case = "True"
shell = "echo 1"

[[tool.poe.tasks._squash.args]]
name = "compress"
options = ["--compress", "-c"]
help = "Compress the layers?"
type = "boolean"
default = false

```

**Comment by nat-n** [comment]
Hi @mgzenitech, little bit hard to understand what you're asking without an explanation, but I guess your intention is that You want the `_squash` task to either do something or nothing depending on a value passed down from the compress flag of the build task?

It looks like all you're missing to make this work is to set the type of the compress arg for `_squash` to be `"string"`, and then I think it'll do what you want. 

So I would suggest the following variation:

```toml
[tool.poe.tasks.build]
sequence = [
  "_build",
  "_squash --compress ${compress}"
]

  [[tool.poe.tasks.build.args]]
  name    = "compress"
  options = ["--compress", "-c"]
  help    = "Compress the layers?"
  type    = "boolean"

[tool.poe.tasks._build]
...

[tool.poe.tasks._squash]
control.expr = "compress"
default      = "pass"
args         = ["compress"]

  [[tool.poe.tasks._squash.switch]]
  case  = "True"
  shell = "echo 1"
```
