### DISCUSSION TITLE
How to include additional files from the task file?

### DISCUSSION THREAD

**Discussion by mgzenitech** [nat-n/poethepoet#146] [Q&A] [answered]
I'll try to write example here:
**pyproject.toml**
```toml
[tool.poe]
include = ["poe_tasks/lint.toml"]
```

**poe_tasks/lint.toml**
```toml
# How to include poe_tasks/lint/dockerfile.toml from this file?
# [tool.poe]
# include = ["lint/dockerfile.toml"]
# Doesn't work here

[tool.poe.tasks.lint]
sequence = [
  "lint:dockerfile"
]
ignore_fail = "return_non_zero"
```

**poe_tasks/lint/dockerfile.toml**
```toml
[tool.poe.tasks."lint:dockerfile"]
control.expr = "len(\"${file_path}\") > 0"

[[tool.poe.tasks."lint:dockerfile".args]]
name = "file_path"
options = ["--file", "-f"]
help = "Relative path to a Dockerfile"

[[tool.poe.tasks."lint:dockerfile".switch]]
case = "False"
shell = "hadolint */**/Dockerfile"

[[tool.poe.tasks."lint:dockerfile".switch]]
case = "True"
shell = "hadolint ${file_path}"

```

**Comment by nat-n** [comment]
Hi @mgzenitech, I'm afraid today it is not possible to include task files from included task files. I think I did it this way because I wasn't sure if it was valuable, and it saved me from having to think about import loops.

If you can present a compelling use case then maybe it can be considered as an enhancement.

**Reply by mgzenitech** [reply]
So the use case would be probably tasks which are sequences to other tasks... Now I have to include every possible subtask toml in main pyproject.toml, for example right now my **pyproject.toml** looks like this:
```toml
[tool.poe]
include = [
  "poe_tasks/_hooks/postinstall.toml",
  "poe_tasks/_hooks/postinstall/install_dive.toml",
  "poe_tasks/_hooks/postinstall/install_node.toml",
  "poe_tasks/_hooks/postinstall/install_node_packages.toml",
  "poe_tasks/build.toml",
  "poe_tasks/dive.toml",
  "poe_tasks/lint.toml",
  "poe_tasks/lint/dockerfile.toml",
  "poe_tasks/lint/env.toml",
  "poe_tasks/lint/markdown.toml",
  "poe_tasks/lint/poetry.toml",
  "poe_tasks/lint/versions.toml",
  "poe_tasks/lint/yaml.toml",
  "poe_tasks/scan.toml"
]
```

**poe_tasks/lint.toml** file:
```toml
[tool.poe.tasks.lint]
sequence = [
  "lint:dockerfile",
  "lint:env",
  "lint:markdown",
  "lint:poetry",
  "lint:versions",
  "lint:yaml"
]
ignore_fail = "return_non_zero"
```

As you can see now I have to include everything in pyproject.toml, but if I could include from task file it's own subtasks files, I would do something like:

**pyproject.toml**
```toml
[tool.poe]
include = [
  "poe_tasks/_hooks/postinstall.toml",
  "poe_tasks/build.toml",
  "poe_tasks/dive.toml",
  "poe_tasks/lint.toml",
  "poe_tasks/scan.toml"
]
```

**poe_tasks/lint.toml** file:
```toml
# Theoretical part
[tool.poe]
include = [
  "lint/dockerfile.toml",
  "lint/env.toml",
  "lint/markdown.toml",
  "lint/poetry.toml",
  "lint/versions.toml",
  "lint/yaml.toml",
]

[tool.poe.tasks.lint]
sequence = [
  "lint:dockerfile",
  "lint:env",
  "lint:markdown",
  "lint:poetry",
  "lint:versions",
  "lint:yaml"
]
ignore_fail = "return_non_zero"
```

That way would be more readable IMHO. Also what would be extra cool if the wildcard would be supported:
**poe_tasks/lint.toml** file:
```toml
# Theoretical part
[tool.poe]
include = ["lint/*.toml"]

[tool.poe.tasks.lint]
sequence = [
  "lint:dockerfile",
  "lint:env",
  "lint:markdown",
  "lint:poetry",
  "lint:versions",
  "lint:yaml"
]
ignore_fail = "return_non_zero"
```

**Reply by nat-n** [reply, marked as answer]
That's not how I Imagined this feature being used, but I see now that it would make sense to support this :). I've added it to my TODO list. I would also entertain a PR along these lines.

**Reply by mgzenitech** [reply]
superb :) Technically even glob pattern include in pyproject.toml would work in my case (and probably should be supported anyway :) ):
**pyproject.toml**
```toml
[tool.poe]
include = ["poe_tasks/**/*.toml"]
```
