### DISCUSSION TITLE
yaml support

### DISCUSSION THREAD

**Discussion by MrSmiler** [nat-n/poethepoet#226] [Ideas]
What do you think about adding yaml support beside toml, what would be the problems ?
One problem i can think is that we can't embed the yaml to pyproject.toml file, so have to include it.
With yaml we can write better nested and complex structures and most ci/cd platforms and even other task runners use this syntax.
This is an example how poe would be in yaml:
```yml
build:
  help: build the product
  control_expr: sys.platform
    - case: win32
      sequence: 
        - shell: "echo Building on windows with version: ${version}"
          interpreter: powershell
        - ref: .package      
    - case: linux
      sequence: 
        - shell: "echo Building on linux with version: ${version}"
          interpreter: bash
        - ref: .package
  args:
    - name: version
      options: 
        - -v
        - --version
      help: product version
      required: true

.package:
  help: package the product binary
  cmd: echo Compress product binary file
```
