### DISCUSSION TITLE
How to get native argument values for postinstall hook?

### DISCUSSION THREAD

**Discussion by mgzenitech** [nat-n/poethepoet#231] [Q&A]
So in my case I'd need to get the value of `--with=` when doing `poetry install` and pass it down to postinstall task. How can I pass the value to my function? For example `--with=core,dev`
```
[tool.poe.poetry_hooks]
post_install = "_post_install"

[tool.poe.tasks._post_install]
sequence = [
  "_postinstall:install_node",
  "_postinstall:install_node_packages"
]

[tool.poe.tasks."_postinstall:install_node_packages"]
control.print_result = true
control.script = "lib.utils.nodejs.are_packages_valid:are_packages_valid"
default = "pass"

[[tool.poe.tasks."_postinstall:install_node_packages".switch]]
case = "False"
script = "lib.utils.nodejs.sync_packages:sync_packages"
```

In this case I'd need to pass this argument to both `lib.utils.nodejs.are_packages_valid:are_packages_valid` and `lib.utils.nodejs.sync_packages:sync_packages`. 

```
def are_packages_valid(dependency_groups: list[str] | None = None) -> bool:
```

```
def sync_packages(dependency_groups: list[str] | None = None) -> None:
```

**Comment by nat-n** [comment]
Hi @mgzenitech, Today this is not possible with the poethepoet poetry plugin.

The first problem with this is to determine whether it's possible with the poetry plugin interface. I'd encourage you to poke around [in here](https://github.com/nat-n/poethepoet/blob/main/poethepoet/plugin.py#L216) if you'f like toto help answer that question.

The second problem is how to structure an API that poe could expose to facilitate configuring this. Ideally without deviating too much from how poe normally handled arguments. How would you expect it to work?

**Reply by mgzenitech** [reply]
For the interface bit we could probably just define arguments next to hook tasks with same name or options? that way people who need those arguments values would get them sorta similar way? I think `--with` is just one of the examples, potentially any argument passed to `poetry install` would be candidate for any postinstall hook. 

```toml
[tool.poe.poetry_hooks]
post_install = "_post_install"

[tool.poe.tasks._post_install]
sequence = [
  "_postinstall:install_node",
  "_postinstall:install_node_packages"
]

[[tool.poe.tasks._post_install.args]]
name = "dependency_groups"
options = [
  "--with"
]
```

that should be in-line with current poe interface right?

**Reply by mgzenitech** [reply]
BTW:
Looks like adding args even now works for internal tasks (_). 
```toml
[tool.poe.tasks._post_install]
sequence = [
  "_postinstall:install_node",
  "_postinstall:install_node_packages"
]

[[tool.poe.tasks._post_install.args]]
name = "dependency_groups"
options = [
  "--with"
]
required = true
```

```
usage: poetry poe _post_install --with DEPENDENCY_GROUPS
poetry poe _post_install: error: the following arguments are required: --with
```

So the only thing that's needed to change in this case would be somehow patching
```
[tool.poe.poetry_hooks]
post_install = "_post_install"
```

to pass all arguments to hooks
