### DISCUSSION TITLE
Dependencies between arguments

### DISCUSSION THREAD

**Discussion by pklejch** [nat-n/poethepoet#242] [Q&A] [answered]
Hi,

is it possible to have dependencies between arguments and conditionally set value of one argument based on value of different argument ?

Example in basic form
```
[tool.poe.tasks.deploy]
cmd = "echo ./deploy ${environment} ${extra}"

    [[tool.poe.tasks.deploy.args]]
    help = "Into which environment to deploy."
    name = "environment"
    required = true
    positional = true

    [[tool.poe.tasks.deploy.args]]
    help = "Extra args."
    name = "extra"
    default = ""
    required = false
    positional = true
```

What I would like to happen:
`poe deploy prod` => `./deploy prod`
`poe deploy dev` => `./deploy dev --argA=123`

=> when deploying to `dev` set and render extra argument `--argA=123`

* I know i can pass additional arguments using `--` => `poe deploy dev -- --argA=123` but I would like to hide this logic behind poe so it happens automatically only for dev environment.
* I know I can use control expression and use switch-case, but I'm already using it in this case (it is not included in example) and I would like to avoid combinatorial explosion.

Thanks

**Comment by nat-n** [comment, marked as answer]
Hi @pklejch, 

I would usually solve this with a switch task though this is a bit verbose.  The problem of how to conditionally include part of a cmd task based on args is something I have encountered but haven't come up with a satisfactory solution for yet (ideas welcome).

Another workaround would be to put the conditional logic in another task and [depend on](https://poethepoet.natn.io/guides/composition_guide.html#composing-tasks-into-graphs) it like so:

```toml
[tool.poe.tasks.deploy]
cmd  = "./deploy $env $options"
args = ["env"]
uses = {"options" = "_deploy_options ${env}"}

[tool.poe.tasks._deploy_options]
expr = "${param} == 'dev' and '--argA=123' or ''"
args = [{ name = "param", positional = true, required = false}]
```

Here I use a [expr](https://poethepoet.natn.io/tasks/task_types/expr.html) for the helper task but you could use [cmd](https://poethepoet.natn.io/tasks/task_types/cmd.html) too. It's not the cleanest solution but it might work for you.

Sometimes the simplest solution is just to use a [shell](https://poethepoet.natn.io/tasks/task_types/shell.html) task with bash flow control, although I usually try to avoid this approach because it's less portable and I don't like the aesthetic of having procedural "code" inside declarative config.
