### DISCUSSION TITLE
Pass arguments to ref tasks

### DISCUSSION THREAD

**Discussion by guillaume-alliander** [nat-n/poethepoet#308] [Q&A] [answered]
Starting to use poe, which is way nicer than my homebrew scripts, thanks for that! 

One thing I am trying to do is to pass parameters (not the value!) in a sequence

```toml
[tool.poe.tasks.all]
sequence = ["format ${check}", "something_without_args"]
args = [{name = "check", type="boolean"}]

[tool.poe.tasks.format]
cmd = 'ruff format ${check:+ --diff}'
args=[{name = "check", type="boolean", help= "Does not correct files, only warns"}]

[tool.poe.tasks.something_without_args]
expr = "not relevant"
```

Now:
- `poe format` => formats file
- `poe format --check` => warns is the file is not formatted
- `poe all` => should format and run the other not relevant task
- `poe all --check` => should warn about formatting and run the other not relevant task

The thing is that `format` requires the string `--check`, not the value (`True`). Currently I get (expectedly) `poe format: error: unrecognized arguments: True`. 

Is there a way to pass arguments as-is, not there value? i have seen that it is possible to pass [values as environment variables](https://poethepoet.natn.io/guides/args_guide.html#arguments-for-sequence-tasks), but that is not the behaviour I am looking for,

**Comment by nat-n** [comment, marked as answer]
Hi @guillaume-alliander, Good question!

Sadly I'm not sure there's a nice way to do exactly what you're asking for.

I guess one nice solution would be if ref tasks also accepted the advanced syntax for parameter expansion `${check:+ --diff}`. I've been planning to make this syntax acceptable in more places so I'll add this to my list.

Another approach would be to implement another missing feature I've been considering for a while (but I'm not yet convinced about a design) which is to allow all unparsed arguments to be accessed via a single variable like "format ${*ALL_ARGS_GO_HERE*}".

Fantasies aside, a not very satisfying workaround could be to use an [switch task](https://poethepoet.natn.io/tasks/task_types/switch.html) like the following example which executes a different sequence depending on whether the `--check` option is provided (untested):

```toml
[tool.poe.tasks.all]
control.expr = "check"
args         = [{name = "check", type="boolean"}]
  [[tool.poe.tasks.all.switch]]
  case     = "True"
  sequence = ["format --diff", "something_without_args"]
  [[tool.poe.tasks.all.switch]]
  sequence = ["format", "something_without_args"]

[tool.poe.tasks.format]
cmd = 'ruff format ${check:+ --diff}'
args=[{name = "check", type="boolean", help= "Does not correct files, only warns"}]

[tool.poe.tasks.something_without_args]
expr = "not relevant"
```

**Reply by guillaume-alliander** [reply]
Thanks for the workaround! it will indeed work. 

Thinking further, I think I would love a passthrough option. Otherwise tasks would need to know how to handle different types of arguments, or ref would need to manipulate arguments to simulate a direct call, and that feels a bit clunky.

Ideally, from a user perspective, I would see something like this design wise:

```toml
[tool.poe.tasks.all]
sequence = [
  { ref = "format", passthrough=["arg1"] },
  { ref = "something_else", passthrough=["arg2"] },
  { ref = "yet_another" },
]
args = [
  {name = "arg1", type="boolean"},
  {name = "arg2", type="string", positional=True},
]

[tool.poe.tasks.format]
cmd = 'blah <normal usage of arg1>'
args = [
  {name = "arg1", type="boolean"},
]

[tool.poe.tasks.something_else]
cmd = 'blah <normal usage of arg2>'
args = [
  {name = "arg2", type="string", positional=True},
]

[tool.poe.tasks.yet_another]
cmd = 'blah'
```

To be even less verbose:
```toml
[tool.poe.tasks.all]
sequence = [
  { ref = "format", passthrough=True }, # would look at "format" and reuse the definition of only the relevant args there
  { ref = "something_else", passthrough=False }, # same, without passing
  { ref = "yet_another" },
]
```
I think this non-verbose option is nicer for the user, because if 2 referenced tasks are trying to use an argument with the same name but different definitions, then the "all" task in my example does not care, and one of the referenced task will rightly complain. That makes it easier for the user.

**Reply by nat-n** [reply]
Thanks for the suggestion @guillaume-alliander

Working with your example, the solution I had in mind was as follows:

```toml
[tool.poe.tasks.all]
sequence = [ "format ${arg1:+ --arg1}",  "something_else ${arg2}",  "yet_another"]
```

Would you foresee any downside to this approach (which is a small change from what's already implemented).
