### DISCUSSION TITLE
Running a task that has "&&" in it doesn't work.

### DISCUSSION THREAD

**Discussion by adhamsalama** [nat-n/poethepoet#85] [Q&A] [answered]
Hello.

I'm trying to add a task that is a couple of commands chain together.
For example, when I typecheck and test my code, I run "mypy. && pytest .", which works fine.
When I add this as a task like this:
```toml
[tool.poe.tasks]
test = "mypy . && pytest ."
```
and run it, I get the following output:
```
poetry run poe test
Poe => mypy . && pytest .
mypy: can't read file '&&': No such file or directory
```

Is there a way to make this work? It would be really useful if I can chain commands.

**Comment by nat-n** [comment, marked as answer]
Hi @adhamsalama,

Absolutely there's a way to make this work. Firstly the issue you're facing it that the default type of task (called a "cmd" task) is a single subprocess without a shell. If you want to invoke the task using a shell (and thereby get support for POSIX shell syntax like `&&`) then you need a shell task which by default will use bash. 

For example the following should do what you want:

```toml
[tool.poe.tasks]
test.shell = "mypy . && pytest ."
```

Note that shell tasks depend on the relevant shell executable on the host system. This means they're slightly less portable than other task types, because windows users might not have bash installed.

However it's also possible to achieve this using a sequence task, which is defined in terms of other tasks. For example you might instead want to do something like:

```toml
[tool.poe.tasks]
types          = "mypy ."
test           = "pytest ."
check.sequence = ["types", "test"]
```

This will give you three separate tasks, the `check` task being equivalent to your original example.

Finally although it's maybe overkill for such a trivial example you can also compose tasks as dependency graphs. The simplest example being making the `test` task require that the `types` task  is always run first like so:

```toml
[tool.poe.tasks]
types          = "mypy ."
test           = { cmd = "pytest .", deps = ["types"] }
```

It's all in the read me ;)

**Reply by adhamsalama** [reply]
Thank you for the answer, it works!
But it seems like VS Code's Toml parser complains about it. Is this normal?
![image](https://user-images.githubusercontent.com/40252995/184245346-b8805151-1fca-4978-8a80-f0d8b1f7913a.png)

**Reply by nat-n** [reply]
Yep, it's normal toml for at least the last couple of versions. That said if the squiggly line is getting to you, toml is quite syntactically flexible so there following to two constructions are equivalent in this case:

```toml
[tool.poe.tasks]
check = { shell = "mypy . && pytest ." }
```

```toml
[tool.poe.tasks.check]
shell = "mypy . && pytest ."
```
