### DISCUSSION TITLE
Running a python program in debug mode

### DISCUSSION THREAD

**Discussion by ghost** [nat-n/poethepoet#90] [Q&A] [answered]
Can we use poethepoet to launch a python program in debug mode? I am trying to use it with VSCode debugger with following launch config.

```json
{
    "name": "Python: Flask",
    "type": "python",
    "request": "launch",
    "module": "poethepoet",
    "args": ["start"],
    "justMyCode": true,
    "jinja": true
}
```

My task definition

```toml
[tool.poe.tasks]
start = { cmd = "python -m apps", help = "Start dev server (press F5 on VSCode)" }
```

It seems like poethepoet is running in debug mode, but the flask server isn't. I can debug my flask app without poethepoet using flask launch config provided by VSCode, but the can't debug it with poethepoet and take advantage of `envfile` feature built into it.
