### DISCUSSION TITLE
Having trouble with tasks with reference

### DISCUSSION THREAD

**Discussion by mshafer-NI** [nat-n/poethepoet#95] [Q&A] [answered]
I have 

```toml
[tool.poe.tasks]
test = "pytest"
stage = "python stage.py"
_publish = "python publish.py"
publish = ["stage", "test", "_publish"]
```

if I run `poetry run poe test` or `poetry run poe stage`, it works as expected; however, if I run `poetry run poe publish` it dies on stage.py with a moduleNotFoundError (on a module I know is in the poetry venv).

I've also tried:

```toml
publish = [
    {ref = "stage"}, 
    {ref = "test"},
    {ref = "_publish"},
]
```

with the same error.

If I do:
```toml
publish = "python publish.py"
```
It does run.

Any ideas what I'm missing?

**Comment by nat-n** [comment, marked as answer]
Hi @mshafer-NI, thanks for the feedback.

I'm afraid this might be a bug in how the sequence task optimises running multiple subtasks with poetry. Possibly related to a known issue on windows environments that is under investigation.

Could you tell me a bit more about your environment?
- OS version
- python version
- poe version
- poetry version
- shell type: cmd? pwsh? bash? wsl?
- method of installation for poe, poetry, and python?

One work around that might be worth trying is to use a script task to directly call a specific method from publish.py e.g.

```toml
_publish.script = "publish:main"
```

Otherwise it might work if you do:

```toml
_publish.script = "poetry run publish.py"
```

Though this is a not a very satisfying solution  as it comes with a cost in complexity & performance.

**Comment by mshafer-NI** [comment]
- OS version
  Windows 10 21H2 (19044)

- python version
  3.7.9
- poe version
  0.16.2
- poetry version
  1.1.15
- shell type: cmd
- method of installation for:
  - poe: pyproj dev dep
  - poetry: their `https://install.python-poetry.org` Python script
  - python: pyenv-win

I tried
```toml
[tool.poe.tasks]
test = "pytest"
stage.script = "stage:main"
_publish = "python publish.py"
publish = ["stage", "test", "_publish"]
```

but calling "poetry run poe publish" still fails on stage on the module.
