### ISSUE TITLE
Slashes from .env files are parsed, newlines are not parsed properly

### ISSUE THREAD

**Issue by monim67** [nat-n/poethepoet#118]
.env file
```bash
VALUE="\\ slash works, \n newlines don't."
```

pyproject.toml
```toml
[tool.poe]
envfile = [".env"]

[tool.poe.tasks]
test = { script = "test:main" }
```

test.py
```py
import os

def main():
    print(os.getenv("VALUE"))
```

When the command is executed, newlines become "n"
```
Poe => test
\ slash works, n newlines don't.
```
