### ISSUE TITLE
Poe is not finding the `*.cmd` executables on Windows

### ISSUE THREAD

**Issue by ni-fgenois** [nat-n/poethepoet#119]
First of all, thank you for maintaining this really cool tool!

# Current behavior

On Windows, the following task fails to run as it can't find `npm.cmd`:
```toml
[tool.poe.tasks.my-node-command]
sequence = [
    {cmd="npm install"}
]
```

Specifying `{cmd="npm.cmd install"}` works fine, and `{cmd="node --help"}` also works as `node.exe` is in the path.

# Expected behavior

`poethepoet` should call `*.cmd` files as if they were regular executables.

# Workaround

Use a `switch` command

```toml
[tool.poe.tasks.my-node-command]
control.expr = "sys.platform"
[[tool.poe.tasks.my-node-command.switch]]
case = "win32"
sequence = [
    {cmd="npm.cmd install"},
]
[[tool.poe.tasks.my-node-command.switch]]
sequence = [
    {cmd="npm install"},
]
```
