### ISSUE TITLE
Help defined in a section not working

### ISSUE THREAD

**Issue by ianepperson** [nat-n/poethepoet#122]
I'm new to poe (thanks for this nice tool!) and it seems that defining the help text within a `pyproject.toml` section isn't working.

``` bash
> poe --version
Poe the poet - version: 0.18.1
```

I think I have my `pyproject.toml` set up correctly:
``` toml
[tool.poe.tasks]
test = {cmd="pytest", help="Run all tests"}
run = {cmd="./manage.py runserver", help="Run the server locally"}

[[tool.poe.tasks.shell]]
cmd = "./manage.py shell_plus"
help = "Run the Django console - THIS DOESN'T DISPLAY"

[[tool.poe.tasks.prod_shell]]
cmd = "./manage.py shell_plus"
help = "Run the Django console for prod - NOR THIS"
env = { ENVIRONMENT = "prod" }
```

However, for the shell tasks there's no help text:

``` bash
> poe -h
Poe the Poet - A task runner that works well with poetry.
version 0.18.1

USAGE
  poe [-h] [-v | -q] [--root PATH] [--ansi | --no-ansi] task [task arguments]

GLOBAL OPTIONS
  -h, --help     Show this help page and exit
  --version      Print the version and exit
  -v, --verbose  Increase command output (repeatable)
  -q, --quiet    Decrease command output (repeatable)
  -d, --dry-run  Print the task contents but don't actually run it
  --root PATH    Specify where to find the pyproject.toml
  --ansi         Force enable ANSI output
  --no-ansi      Force disable ANSI output

CONFIGURED TASKS
  test           Run all tests
  run            Run the server locally
  shell
  prod_shell
```
