### ISSUE TITLE
Doesn't respect environment over .env file

### ISSUE THREAD

**Issue by nitedani** [nat-n/poethepoet#129]
For example:
```
[tool.poe]
envfile = ".env"
[tool.poe.tasks]
migrate = "alembic -x dbname=$POSTGRES_URL upgrade head"
```
Issue:
If I run `poetry run poe migrate` then poe will use the POSTGRES_URL set in the .env file, not POSTGRES_URL set in the environment.

Expectation:
`poetry run poe migrate` first tried to find POSTGRES_URL in the environment, and falls back to looking it up in the .env file only if POSTGRES_URL is not set in the environment

**Comment by nat-n** [comment]
Hi @nitedani, thanks for the feedback.

It works that way because that's what I thought made sense at the time. However I would be interested if you could point to examples of other prominent tools that take the opposite approach?

I guess it's not quite what you want but defining an argument for the task like so might be a workaround:

```toml
[tool.poe.tasks]
migrate = "alembic -x dbname=$POSTGRES_URL upgrade head"
args = [{ name = "POSTGRES_URL", options = ["--url"], default = "${POSTGRES_URL}" }]
```

```sh
poe migrate --url="postgresql://..."
```
