### ISSUE TITLE
Poe breaks when directory has spaces in the name

### ISSUE THREAD

**Issue by ThatXliner** [nat-n/poethepoet#131]
At least, I think that’s what is breaking Poe. I’m on macOS, more information will be provided during the weekend. I suspect it’s something to do with quoting the executable but that shouldn’t be a problem (unless shell is enabled?)

**Comment by nat-n** [comment]
Hi @ThatXliner,

Did you work out what was going wrong?

I just did a quick test on macOs and I see the following tasks all work as expected:

```toml
[tool.poe.tasks]
test1 = "test\\ test/test.sh OK"
test2 = "'test test/test.sh' OK"
test3 = "\"test test/test.sh\" OK"
```

I also tried renaming the project directory itself to have a space in the name and didn't encounter any issue.

I'm going to close this issue for now, but feel free to comment with more details if you find something specifically wrong.
