### ISSUE TITLE
Can't use  os.path.isdir in case

### ISSUE THREAD

**Issue by mgzenitech** [nat-n/poethepoet#134]
```toml
[tool.poe.tasks.post_install]
control.script = "os.path:isdir('.venv/node')"

[[tool.poe.tasks.post_install.switch]]
case = "False"
sequence = [
  ...
]

[tool.poe.poetry_hooks]
post_install = "post_install"
```

Is always getting me:
Error: Control value '' did not match any cases in switch task 'post_install'. 
Cancelling command due to failed hook task
