### ISSUE TITLE
Can't in-lined tasks from another file with cwd

### ISSUE THREAD

**Issue by roger-duthie-pivotal** [nat-n/poethepoet#158]
### Summary

If trying to use the syntax documented [here](https://poethepoet.natn.io/guides/include_guide.html#setting-a-working-directory-for-included-tasks):

```toml
[[tool.poe.include]]
path = "my_subproject/pyproject.toml"
cwd  = "my_subproject"
```

... there is an exception if any tasks are defined "in-line" like:

```toml
[tool.poe.tasks]
mytask = "mycooltask"
myothertask = "myothertask"
```

The issue is that these tasks are loaded as strings so that on line 291 `config.py` the `task_def` is a string and on line 305 there is a type error when `task_def["cwd"]` is attempted.

### Possible solution
To convert any string tasks to objects like: 

```python
for task_name, task_def in tasks.items():
    if isinstance(task_def, str):
        task_def = {
            "cmd": task_def
        }
        tasks[task_name] = task_def  # Not sure if this is necessary or if the dictionary will be updated...
    [...]
```

I can create a PR at some point if you think this is: 

- [ ] Real
- [ ] A good enough fix
