### ISSUE TITLE
Including square brackets in arguments does not pass to poe

### ISSUE THREAD

**Issue by stephen-spar** [nat-n/poethepoet#191]
- version: 0.24.4
- system: macOS

## Issue

When including square brackets in an argument (either positional or non-positional), it seems to break how poe sends along the arguments to the actual task.

## Reproduction

```toml
# pyproject.toml

[tool.poe.tasks.hello]
cmd = "echo $name"
args = [{ name = "name", positional = true }]
```

This works as expected:

```bash
poe hello "world"
Poe => echo world
world
```

This does not:

```bash
poe hello "world[extra]"
Poe => echo

```

## Use Case

I have a sequence command to install poetry packages (`poe add`) which runs `poetry add $package`, and then a second command to sync them with my dev container:

```toml
[tool.poe.tasks.add]
sequence = [{ cmd = "poetry add $package" }, { ref = "sync-dev-deps" }]
args = [{ name = "package", positional = true }]
```

All good if I'm trying to install something like `django` or `numpy`, but for something with "extra" packages (ex. `django-anymail[mailgun]`), I'm not able to utilize this command and need to fall back to `poetry add "django-anymail[mailgun]"`.

Hopefully this isn't documented anywhere - if it is, feel free to point me in that direction and close the issue! Thanks so much for the awesome package, fits my needs exactly.
