### ISSUE TITLE
poetry_hooks with switch tasks by named argument

### ISSUE THREAD

**Issue by StripedMiha** [nat-n/poethepoet#193]
Hi! I was very interested in your tool and decided to implement it into the project.

In my project, I want to add a hook with a pre-commit install setup along with executing the poetry install --with dev command.
Here is my `puproject.toml` with dependencies divided into groups:
```toml
[tool.poetry.dependencies]
python = "^3.10"
...
poethepoet = "^0.24.4"

[tool.poetry.group.dev.dependencies]
...
pre-commit = "^3.2.0"


[tool.poetry.group.test.dependencies]
...
```

I have a working solution for this purpose, which is always executed when entering the `poetry install` command. 
```toml
[tool.poe.poetry_hooks]
post_install = "pre_commit_install"

[tool.poe.tasks.pre_commit_install]
help = "pre-commit pre install"
cmd = "pre-commit install"
```

However, I need the hook to be executed only when entering the `poetry install` command with the `--with dev` argument.

Here is my vision of `pyproject.toml`, for such functionality:

```toml
[tool.poe.poetry_hooks]
post_install = "pre_commit_install"

[tool.poe.tasks.pre_commit_install]
help = "pre-commit pre install"
default = "pass"
control.expr = "with"
args = ["with"]

    [[tool.poe.tasks.pre_commit_install.switch]]
    case = "dev"
    cmd = "pre-commit install"
```

When I enter the command `poetry install --with dev`, I get the following error:

<img width="725" alt="image" src="https://github.com/nat-n/poethepoet/assets/87929089/52480037-0600-4943-914a-273dd4b412f6">

Please help me figure out what went wrong.

Thanks!

**Comment by nat-n** [comment]
Hi @StripedMiha,

> However, I need the hook to be executed only when entering the poetry install command with the --with dev argument.

I'm afraid limiting poetry hooks to invocations including specific arguments is not currently supported. Your workaround using a switch task is interesting, and might even work.

I believe the error you're getting from the `expr` task is because an expr task content is actually interpreted as subset of python, and as it happens `with` is a keyword in python, so the validation fails.

You should be able to avoid this particular error by mapping the argument to a different name with something like:

```toml
control.expr = "deps_group"
args = [{ name = "deps_group", options = ["--with"] }]
```

Please let me know if you get it working :)

**Comment by StripedMiha** [comment]
@nat-n 
Thanks for the advice. 

But I'm afraid I don't quite understand how this should work, but this option does not catch the argument correctly and gives a default response.
```toml
[tool.poe.tasks.pre_commit_install]
help = "pre-commit pre install"
control.expr = "deps_group"
args = [{ name = "deps_group", options = ["--with"] }]

    [[tool.poe.tasks.pre_commit_install.switch]]
    case = "dev"
    cmd = "pre-commit install"

    [[tool.poe.tasks.pre_commit_install.switch]]
    cmd = "echo abc"
```
The response from such a command now does not fall with an error, but the switcher does not catch the argument
<img width="583" alt="image" src="https://github.com/nat-n/poethepoet/assets/87929089/8ee3ff64-90fd-49dd-badd-d08bfc06f7f1">
