### ISSUE TITLE
Allow envars and shell commands usage in "include" path

### ISSUE THREAD

**Issue by jaklan** [nat-n/poethepoet#203]
Let's imagine a monorepo structure like:
```
pyproject.toml
projects/
-- foobar/
---- pyproject.toml
```
In `pyproject.toml` we define monorepo-wide commands, which are imported in all project-level `pyproject.toml`s. 

To import the global commands, in `projects/foobar/pyproject.toml` we need to specify:
```toml
[tool.poe]
include = "../../pyproject.toml" 
```
which is pretty inconvenient and error-prone:
- it's very easy to specify a wrong file when you refer to a parent directory a few levels up
- the repo / project structure can change and you have to remember to update the path
   - it's tricky to notice the error in such situation because of:
   
      > If a referenced file is missing then poe ignores it without error, though failure to read the contents will result in failure.
      
   - by coincidence you can even import a wrong file

I wish it could be possible to add a support for envars and shell commands in `include`, so we can rely on a more robust solution like:
```toml
[tool.poe]
include = "$(git rev-parse --show-toplevel)/pyproject.toml" 
```
