### ISSUE TITLE
Feature: load .env

### ISSUE THREAD

**Issue by ThatXliner** [nat-n/poethepoet#22]
`.env` is a file that specifies the environment variables that should be loaded. AFIAK Poetry doesn't load these. Will `poe` do, though?

**Comment by ThatXliner** [comment]
Currently, my tasks look like this: 
```toml
[tool.poe.tasks]
    [tool.poe.tasks.run]
    shell = "if [ -r .env ]; then eval $(grep -v '^#' .env | xargs) poetry run python -m slashtilities; else echo 'You need to make a .env'; fi"
    help = "Run the bot"
```
https://github.com/ThatXliner/slashtilities/blob/4090f359cd72fa8ec55fe7f1a91bd76474100cb6/pyproject.toml#L22-L25
