### ISSUE TITLE
How to share variables among tasks?

### ISSUE THREAD

**Issue by fritz-trawa** [nat-n/poethepoet#236]
I haven't been able to find out how to share variables among tasks. What I mean is this

```toml
[tool.poe.tasks]
src = "./some/string/"

[tool.poe.tasks.typecheck]
cmd = "mypy $my_src" <-- THIS

[tool.poe.tasks.lint]
cmd = "ruff $my_src"

```

surely it must be possible, but how? Thanks

**Comment by nat-n** [comment]
Hi @fritz-trawa,

If I understand your question correctly there are two mechanisms appropriate for setting a variable in one place for use by multiple tasks.

1. [Global environment variables](https://poethepoet.natn.io/global_options.html#global-environment-variables)
    ```toml
    [tool.poe.env] <-- THIS
    my_src = "./some/string/"
      
    [tool.poe.tasks.typecheck]
    cmd = "mypy $my_src"
      
    [tool.poe.tasks.lint]
    cmd = "ruff $my_src"
     ```
2. Create a [dotenv file](https://poethepoet.natn.io/tasks/options.html#loading-environment-variables-from-an-env-file) and reference it from each task or as a global option.

Does that solve your problem?
