### ISSUE TITLE
Error executing the task when the documentation has multiple lines

### ISSUE THREAD

**Issue by taconi** [nat-n/poethepoet#239]
## Description of the bug

When I create a task that has its documentation (**help**) with more than one line, no error is displayed when listing the tasks configured with the `poe --help` command, but when executing this task an error appears, preventing your concussion.

### Error displayed

``` shell
Error: Invalid task 'fmt'
	 | Help messages must not contain line breaks
```

### Dependencies

The following versions were used for testing:

| dependency | version                              |
|------------|--------------------------------------|
| python     | **3.12.5**                           |
| poetry     | **1.8.3**                            |
| poethepoet | **0.26.1** - **0.27.0** - **0.28.0** |

<details>
<summary>
	<b>pyproject.toml</b> file with the  <b>fmt </b> task that has documentation with more than one line
</summary>

``` toml
[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "3.12.5"
poethepoet = "^0.28.0"
black = "^24.8.0"

[tool.poe.tasks.fmt]
help = """\n
	 Use "poe fmt" to format the code.

	 Examples:
	   # Format all files
	   poe fmt
"""
cmd = "black -S -l 79 $PATH"
[tool.poe.tasks.fmt.args.PATH]
options = ["-p", "--path"]
default = "."
help = """\n
	 Change the path that will be formatted.

	 Examples:
	   # Formatting a specific path
	   poe fmt -p tests
"""

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

</details>

### Steps

1. Install project dependencies:

``` shell
poetry install
```

2. List the successfully configured tasks:

``` shell
poetry run poe --help
```

<details>
<summary>
	Full output of <b>poetry run poe --help</b> command
</summary>

``` shell
Poe the Poet - A task runner that works well with poetry.
version 0.28.0

Usage:
  poe [global options] task [task arguments]

Global options:
  -h, --help            Show this help page and exit
  --version             Print the version and exit
  -v, --verbose         Increase command output (repeatable)
  -q, --quiet           Decrease command output (repeatable)
  -d, --dry-run         Print the task contents but don't actually run it
  -C PATH, --directory PATH
						Specify where to find the pyproject.toml
  -e EXECUTOR, --executor EXECUTOR
						Override the default task executor
  --ansi                Force enable ANSI output
  --no-ansi             Force disable ANSI output

Configured tasks:
  fmt

	 Use "poe fmt" to format the code.

	 Examples:
	   # Format all files
	   poe fmt

	-p, --path

	 Change the path that will be formatted.

	 Examples:
	   # Formatting a specific path
	   poe fmt -p tests
 [default: .]
```

</details>

3. Running task with error:

``` shell
poetry run poe fmt
```

<details>
	<summary>
		Full error output from <b>poe fmt</b> command
	</summary>

``` shell
Poe the Poet - A task runner that works well with poetry.
version 0.28.0

Error: Invalid task 'fmt'
	 | Help messages must not contain line breaks

Usage:
  poe [global options] task [task arguments]

Global options:
  -h, --help            Show this help page and exit
  --version             Print the version and exit
  -v, --verbose         Increase command output (repeatable)
  -q, --quiet           Decrease command output (repeatable)
  -d, --dry-run         Print the task contents but don't actually run it
  -C PATH, --directory PATH
						Specify where to find the pyproject.toml
  -e EXECUTOR, --executor EXECUTOR
						Override the default task executor
  --ansi                Force enable ANSI output
  --no-ansi             Force disable ANSI output

Configured tasks:
  fmt

	 Use "poe fmt" to format the code.

	 Examples:
	   # Format all files
	   poe fmt

	-p, --path

	 Change the path that will be formatted.

	 Examples:
	   # Formatting a specific path
	   poe fmt -p tests
 [default: .]
```

</details>
