### ISSUE TITLE
[BUG] Error: executable 'python' could not be found

### ISSUE THREAD

**Issue by tzah4748** [nat-n/poethepoet#276]
**Environment:**
Docker based on ubuntu 22.04 with python3 and python3-pip installed via apt-get
Obviously installing poethepoet using pip.
Poe the Poet - version: 0.32.2

**Bug Description:**
When running a simple `cmd` task that contains `args` the following error appears:
![Image](https://github.com/user-attachments/assets/bf8f203e-308a-40a5-a785-af41840769b8)

**Suggestion on how to fix:**
In the file: https://github.com/nat-n/poethepoet/blob/main/poethepoet/task/expr.py#L87 use `sys.executable` instead of 'python'
The command attempts to executes "python", however "python" is not a thing in my environment, only python3.
In order to not restrict this to a specific OS/Environment, its safer to use `sys.executable`.

**Comment by nat-n** [comment]
Hi @tzah4748, thanks for reporting this

I see there's a need to detect when `python` is not available but `python3` is. Unfortunately falling back to `sys.executable` would cause unexpected behavior in cases where the python used for the `poe` executable is not that same as used in the target virtual environment.

I'll look into fixing this.

**Comment by nat-n** [comment]
Hi @tzah4748, I just got around to looking at this, and I could use some help understanding what exactly is going on here.

Are you using poe in a project without poetry or another virtual environment? I would expect a virtual environment to always include a `python` executable.

The only reason I can think of that this would happen is if you're using the SimpleExecutor (no venv) with an expr or script task, or a shell task with a python interpreter. I can't see how this would happen with a plain cmd task unless the task content specifically includes a reference to python.

Could you share more details about the task/project?

**Comment by tzah4748** [comment]
I described the environment as simple as can be in the initial post :)
- The project is not using poetry.
- No `venv` is being used.
- I use a clean Ubuntu:22.04 docker image where python and pip are installed using apt-get (`apt-get update && apt-get install -y python3 python3-pip`).
- Inside the container I also install poethepoet from pip (`pip install poethepoet`).
- I run `poe` inside the container where only `python3` is a keyword that launches the installed python.

I'll provide some concrete example of tasks that fail for me.

Running `poe assert-license` fails.
```toml
[tool.poe.tasks._unlicensed-files]
help = "List files that do not contain the LICENSE file"
imports = ["pathlib"]
expr = "[file.absolute() for file in pathlib.Path('src').glob('**/*.py') if not file.read_text().startswith(pathlib.Path('LICENSE').read_text()) ]"

[tool.poe.tasks.assert-license]
uses = { FILES = "_unlicensed-files" }
expr = "print(${FILES}) is None and not ${FILES}"
assert = true
```

Another case where this gets even more annoying, is trying to put another task in the `deps` as shown in the following example:
```toml
[tool.poe.tasks.lint]
help = "Run flake8 linter on the source code and tests"
deps = ["assert-license"]
cmd = "flake8 ${POE_ROOT}/src ${POE_ROOT}/tests"
```
