### ISSUE TITLE
Global environment variables

### ISSUE THREAD

**Issue by pawamoy** [nat-n/poethepoet#3]
I'm trying poethepoet by migrating my Makefile to poe tasks 🙂 

One thing I do in the Makefile is to declare the paths to directories to be scanned by code quality tools:

```makefile
PY_SRC = src/ tests/

check-code-quality:
	@flake8 $(PY_SRC)

```

I would like to do the same with poe:

```toml
[tool.poe.env]
PY_SRC = "src/ tests/"

[tool.poe.tasks]
check-code-quality = "flake8 $PY_SRC"
```

Based on the README, I don't think this is possible yet.
