### ISSUE TITLE
Environment variable substitution

### ISSUE THREAD

**Issue by fdaguin** [nat-n/poethepoet#33]
## Is your feature request related to a problem?

I want to define environment variables for tasks with values that will be substituted with already defined environment variables.

## Describe the solution you'd like

Let's consider this dummy task:

```toml
[tool.poe.tasks]
"path" = { cmd = "echo $MY_PATH", env = { MY_PATH = "$PATH" }}
```

When a run `poe path`, I want the value of `$PATH` to be resolved instead of only echoing `$PATH` as a string.

## Describe alternatives you've considered

Using shell tasks by:

- defining the environment variable inline: no success

  ```toml
  [tool.poe.tasks]
  "path" = { shell = "MY_PATH=$PATH echo $MY_PATH" }
  ```

- defining the environment variable with Poe: no success

  ```toml
  [tool.poe.tasks]
  "path" = { shell = "echo $MY_PATH", env = { MY_PATH = "$PATH" }}
  ```
