### ISSUE TITLE
Sequences can't handle arguments :(

### ISSUE THREAD

**Issue by rjurney** [nat-n/poethepoet#37]
I've read the code and I can't find any way to make a sequence accept an argument. The code actually says to throw an exception if any extra arguments are given :(

I need to run the task `setup-artifacts` before I run the task `poetry add`. Since `poetry add` takes an argument I need to feed it to the last command in the list. This seems unsupported. I read the code and I get lost but this tells me `SequenceTasks` don't accept arguments: https://github.com/nat-n/poethepoet/blob/c5ac6cf3f9561f3891f620dc576e707cbcf441f0/poethepoet/task/sequence.py#L53-L72

My `pyproject.toml` reads:

```python
[tool.poe.tasks]
setup-artifacts = "scripts/setup_artifacts.sh setup-poetry"
add = [{ref="setup-artifacts"}, { cmd = "poetry add" }]
```

I run `poe add moto` and I get:

```bash
poe add moto
```

```bash
Poe the Poet - A task runner that works well with poetry.
version 0.10.0

Error: Sequence task 'add' does not accept arguments

USAGE
  poe [-h] [-v | -q] [--root PATH] [--ansi | --no-ansi] task [task arguments]

GLOBAL OPTIONS
  -h, --help     Show this help page and exit
  --version      Print the version and exit
  -v, --verbose  More console spam
  -q, --quiet    Less console spam
  -d, --dry-run  Print the task contents but don't actaully run it
  --root PATH    Specify where to find the pyproject.toml
  --ansi         Force enable ANSI output
  --no-ansi      Force disable ANSI output

CONFIGURED TASKS
  setup-artifacts
  add
```

This makes me a sad panda :( What would I need to do to make `poe` take arguments to sequences? Maybe put an argument for them like `args_to=2` to reference the command in the sequence?

**Comment by nat-n** [comment]
Hi @rjurney, thanks for the feedback!

Yes, I skipped on supporting arguments for sequences the first time round for lack of clarity on how it could work without inelegance. I have a couple of ideas though.

One way to achieve this would be via the task graph feature discussed [here](https://github.com/nat-n/poethepoet/issues/26), for which there is already an experimental implementation in pre-release. I say experimental but it's not really documented or well tested yet.

So with the pre-release version I think you could do something like the following:

```toml
[tool.poe.tasks]
setup-artifacts = "scripts/setup_artifacts.sh setup-poetry"
add = { cmd = "poetry add", "deps" = ["setup-artifacts"] }
```

This example defines a minimalist task graph, with add being the sync node, that requires `setup-artifacts` to be run first. Let me know if this already works for you?

The other way is something I thought of recently but haven't yet tried which is to build upon the named arguments feature (also in pre-release) and make `ref` tasks support passing arguments (in the same way as "deps" or "uses" references do for task graphs), so it would look something like:

```toml
[tool.poe.tasks]
setup-artifacts = "scripts/setup_artifacts.sh setup-poetry"
_poetry_add = "poetry add"

  [tool.poe.tasks.add]
  sequence = ["setup-artifacts", "poetry add $target"]
  args = ["target"]
```

Which would then be invoked as `poe add --target moto`.

**Comment by Haffi921** [comment]
``I have a similar issue. For simplicity, let's say I'd like to chain-run `isort` and `black` both on a specific file or folder under a rule "format".

What I can do already is a general task for the whole project, like this:
```toml
[tool.poe.tasks]
isort = "isort ."
black = "black ."
format = ["isort", "black"]
```

OR statically specify files or folders
```toml
[tool.poe.tasks]
format_this_specific_file_why_would_I_ever_do_this = [
    {cmd = "isort ./src/util/error.py"},
    {cmd = "black ./src/util/error.py"}
]
```

But I cannot dynamically give a file or folder for both task to run on. I imagine in your proposal this would be the solution?
```toml
[tool.poe.tasks]
....

    [tool.poe.tasks.format]
    sequence = ["isort $target", "black $target"]
    args = ["target"]
```
Is there already a method I can use to get these desired results that I am missing?

-----------

I can also imagine another solution for simple cases. Something like this:
```toml
[tool.poe.tasks]
format = ["isort $1", "black $1"]
```
Where `$N` where N is a number from [1, 2, 3,... ] of order of arguments given. I don't know the specifics if this would clash with any other `poe` features. But if not, maybe these two solutions could be implemented. One for dead-simple cases and the other one for when you need a bit more control/explicitness.

**Comment by nat-n** [comment]
@rjurney  As of v0.11.0 (just released) you can now do something like:

```toml
[tool.poe.tasks]
setup-artifacts = "scripts/setup_artifacts.sh setup-poetry"

[tool.poe.tasks.add]
sequence = [{ref="setup-artifacts"}, { cmd = "poetry add $package" }]
args = [{ name = "package", positional = true }]
```

which could be invoked like:

```bash
poe add moto
```

I hope this works for you :)

@Haffi921 Your example should work now too
