### ISSUE TITLE
Multiple commands in one task

### ISSUE THREAD

**Issue by pawamoy** [nat-n/poethepoet#4]
How would I write the following rule as a poe task?

```makefile
.PHONY: clean
clean:  ## Delete temporary files.
	@rm -rf .coverage* 2>/dev/null
	@rm -rf .mypy_cache 2>/dev/null
	@rm -rf .pytest_cache 2>/dev/null
	@rm -rf build 2>/dev/null
	@rm -rf dist 2>/dev/null
	@rm -rf pip-wheel-metadata 2>/dev/null
	@rm -rf site 2>/dev/null
	@find . -type d -name __pycache__ | xargs rm -rf 2>/dev/null
	@find . -name "*.rej" -delete 2>/dev/null
```

I'd be tempted to do this:

```toml
[tool.poe.tasks.clean]
cmd = """
    rm -rf
        .coverage*
        .mypy_cache
        .pytest_cache
        build
        dist
        pip-wheel-metadata
        site
        2>/dev/null;
    find . -type d -name __pycache__ | xargs rm -rf 2>/dev/null;
    find . -name "*.rej" -delete 2>/dev/null;
"""
```

...but then I think the `;` would be considered as arguments instead of command separator.

If I use a `shell` type instead:

```toml
[tool.poe.tasks.clean]
shell = """
    rm -rf \
        .coverage* \
        .mypy_cache \
        .pytest_cache \
        build \
        dist \
        pip-wheel-metadata \
        site \
        2>/dev/null;
    find . -type d -name __pycache__ | xargs rm -rf 2>/dev/null;
    find . -name "*.rej" -delete 2>/dev/null;
"""
```

...I guess I now have to escape the new lines?

Maybe I should keep each command on its own line, and separate them with `;`?

```toml
[tool.poe.tasks.clean]
shell = """
    rm -rf .coverage* 2>/dev/null;
    rm -rf .mypy_cache 2>/dev/null;
    rm -rf .pytest_cache 2>/dev/null;
    rm -rf build 2>/dev/null;
    rm -rf dist 2>/dev/null;
    rm -rf pip-wheel-metadata 2>/dev/null;
    rm -rf site 2>/dev/null;
    find . -type d -name __pycache__ | xargs rm -rf 2>/dev/null;
    find . -name "*.rej" -delete 2>/dev/null;
"""
```

I could also define "hidden" tasks and make a sequence of them, but I would need to declare them as `shell` type:

```toml
[tool.poe.tasks]
default_task_type = "shell"
_rm_coverage = "rm -rf .coverage* 2>/dev/null"
_rm_mypy = "rm -rf .mypy_cache 2>/dev/null"
_rm_pytest = "rm -rf .pytest_cache 2>/dev/null"
_rm_build = "rm -rf build 2>/dev/null"
_rm_dist = "rm -rf dist 2>/dev/null"
_rm_wheel = "rm -rf pip-wheel-metadata 2>/dev/null"
_rm_site = "rm -rf site 2>/dev/null"
_rm_pycache = "find . -type d -name __pycache__ | xargs rm -rf 2>/dev/null"
_rm_rej = "find . -name '*.rej' -delete 2>/dev/null"
clean = [
    "_rm_coverage",
    "_rm_mypy",
    "_rm_pytest",
    "_rm_build",
    "_rm_dist",
    "_rm_wheel",
    "_rm_site",
    "_rm_pycache",
    "_rm_rej",
]
```

But then, the ideal would be to be able to define the array task type locally (which I think is not possible yet):

```toml
[tool.poe.tasks.clean]
array_item_task_type = "shell"
ignore_fail = true
sequence = [
    "rm -rf .coverage* 2>/dev/null",
    "rm -rf .mypy_cache 2>/dev/null",
    "rm -rf .pytest_cache 2>/dev/null",
    "rm -rf build 2>/dev/null",
    "rm -rf dist 2>/dev/null",
    "rm -rf pip-wheel-metadata 2>/dev/null",
    "rm -rf site 2>/dev/null",
    "find . -type d -name __pycache__ | xargs rm -rf 2>/dev/null",
    "find . -name '*.rej' -delete 2>/dev/null",
]
```

What do you feel is the most maintainable way? Which one is the less error-prone? Any thought is welcome here 🙂
