### ISSUE TITLE
Instantiate breaks using Deep Keys

### ISSUE THREAD

**Issue by wsidl** [nat-n/poethepoet#41]
I'm trying to setup some commands and some require a number of Environment Variables, so I decided to try the Deep Keys method described at https://github.com/nat-n/poethepoet#environment-variables

Tasks configured:

```toml
[tool.poe.tasks]
init_db    = "alembic upgrade head"
dev.cmd    = "python -m flask run -p 5001"
dev.env    = { FLASK_ENV="development", FLASK_DEBUG="1" }
```

this breaks with `poethepoet.exceptions.PoeException: Cannot instantiate unknown task 'flask_dev'` from `poethepoet/task/base.py:L85`

Replacing the "dev" task with:

```toml
dev        = { cmd="python -m flask run -p 5001", env = { FLASK_ENV="development", FLASK_DEBUG="1" }}
```

fixes the problem

---

`python -V` = "Python 3.9.7"
`poe --version` = "version: 0.10.0"

**Comment by nat-n** [comment]
Hi @wsidl,

Thanks for reporting this. I've reproduced the issue with v0.10.0. I'm not sure of the cause, but the issue appears to have been fixed already in the pre-release for v0.11.0, so I'd suggest using that for now, e.g. `pip install poethepoet==0.11.0b6`

Let me know whether this resolves your issue :)

**Comment by wsidl** [comment]
Thanks for checking. I can confirm upgrading to `0.11.0b6` does indeed work.

---

Set version in pyproject.toml:
```toml
[tool.poetry.dependencies]
poethepoet = "^0.11.0b6"

[tool.poe.tasks]
dev.cmd    = "python -m flask run -p 5001"
dev.env    = { FLASK_ENV="development", FLASK_DEBUG="1" }
```

Then run poetry commands
```bash
poetry lock
poetry install
```

Then I am able to run my tasks successfully with Deep Keys

```
> poe dev                                                                                                                                                  
Poe => python -m flask run -p 5001
 * Serving Flask app 'server' (lazy loading)
 * Environment: development
...
```
