### ISSUE TITLE
interactive clients tend not to launch in poe

### ISSUE THREAD

**Issue by gangofnuns** [nat-n/poethepoet#64]
Hello -- 

I've been using poe to launch a few console tools written in shell recently. 
It works!

However, I've noticed that when I run interactive tools like mysql or psql clients, 
it fails to launch them, even in simple scenarios. 

Is this a known issue?  Curious if there might be a workaround. 

Thanks for the tools!   Cheers --

**Comment by ThatXliner** [comment]
Maybe we could use pexpect for spawning stuff. It’s used by Poetry for the `poetry shell` command[^1]. Here’s an example of pexpect: https://github.com/pexpect/pexpect/blob/master/examples/python.py

[^1]: https://github.com/python-poetry/poetry/blob/4838c9fe9645c62353be569a96765c693f03f1a3/src/poetry/utils/shell.py#L71

**Comment by gangofnuns** [comment]
oh!  I like that idea a lot!   LMK if you need anything.

Happy to be the guinea pig.

**Comment by nat-n** [comment]
Hi @gangofnuns, thanks for the feedback.

I've encountered similar issues with this myself, but haven't quite gotten to the bottom of it.

What I know is that the following does give you an interactive REPL as expected:
```toml
[tool.poe.tasks.repl]
cmd = "python"
```

and the same works for script tasks:
```python
# tasks.py

def repl():
    while True:
        print(eval(input(">>> ")))
```
```toml
# pyproject.toml

[tool.poe.tasks.repl]
script = "tasks:repl"
```

But it doesn't work for shell tasks:
```toml
[tool.poe.tasks.repl]
shell = "tasks:repl"
```
This is because shell tasks work by passing the task content into the shell executable via stdin – which is the most reliable cross shell/platform method I'm aware of, but does rule out directly interacting with processes inside the child shell via the terminal.

Are you encountering this issue specifically with shell tasks or is there something about some other tool that works differently with cmd tasks as well?

I guess pexpect works by using a background thread to manage communication with the shell subprocess? I wouldn't rule out adopting it as an option for shell tasks specifically, though it's quite heavy weight and a bit complex, so I'm a little hesitant. I'd like to better understand the use cases and how this stuff works before committing to such an approach.

**Comment by johnraz** [comment]
I worked around this issue by using command instead of shell.

```
  [tool.poe.tasks.interactive_command]
  cmd = "bash -c interactive-command"
```

**Comment by dbohdan** [comment]
You can also use an expression task and `subprocess`.

```toml
[tool.poe.tasks.interactive]
# Do not raise an exception if the command fails,
# just pass on its exit code.
expr = '''
  sys.exit(subprocess.run(
      ["vim", "pyproject.toml"]
  ).returncode)
'''
imports = ["subprocess", "sys"]
```
