### ISSUE TITLE
Extra arguments apart from what is declared, are not attached correctly

### ISSUE THREAD

**Issue by smac89** [nat-n/poethepoet#69]
I just want to add a disclaimer: _I'm not sure whether `poe` was designed the accept extra arguments beyond what was declared for a task, but I noticed that supplying extra args after `--` seems to include the extra arguments, so that's what I was trying here_

For example, given the following task declaration:

```toml
[tool.poe.env]
PYTHONPATH = "${PWD}/examples"
DJANGO_SETTINGS_MODULE = "config.settings"

[tool.poe.tasks.migrate]
cmd = "django-admin migrate --pythonpath ${PWD}/examples/$example"
args = [{name = "example", default = "my_app_example", positional = true}]
envfile = ".env"
```

If I run it using `poe migrate -- --help`, poe will translate it to:

```sh
django-admin migrate --pythonpath /home/username/projects/my_django_app/examples/--help
```

This causes an error because as you can see, there is no space between the last argument and `--help`, however without the extra `-- --help`, everything works, but I can't pass more arguments to the command.

Please help me know if this is defined behavior and how to work around it, or whether it's a bug. Thanks
