### ISSUE TITLE
Script execution does not relay exit code

### ISSUE THREAD

**Issue by cwichel** [nat-n/poethepoet#71]
# Environment 
* **OS:** Windows 10 
* **Poetry:** 1.2.0b1
* **POE:** 0.13.1

# Issue 
If you have a script that returns an error as system exit code, for example: 
```python 
include sys

def test_script() -> None:
    sys.exit(1) 
```
In a file called `sample.py` in your repository root, and configured as follows on the `pyproject.toml` file: 
```toml
[tool.poe.tasks]
    [tool.poe.tasks.test-script]
    help    = "Check if the returnvalue is being relayed"
    script  = "sample:test_script"
```

You'll see (windows): 
```cmd
> poe test-script
Poe => test-script
> echo %errorlevel%
0
```

Instead of: 
```cmd 
> python .c "import sample as s; s.test_script()"
> echo %errorlevel%
1
```

Is this intended? Is there a way to relay the returncode from the failed script out of poe?
