### ISSUE TITLE
[Linux] Setting LD_LIBRARY_PATH does not work for detecting DLLs 

### ISSUE THREAD

**Issue by Interpause** [nat-n/poethepoet#72]
Certain packages, such as [onnxruntime](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements) rely on external DLLs such as CUDA.

To provide some context, on Windows, Python uses `%PATH%` or `os.add_dll_directory` when searching for DLLs. On Linux, Python uses `$LD_LIBRARY_PATH` when searching for DLLs.

Based on <https://stackoverflow.com/questions/856116/changing-ld-library-path-at-runtime-for-ctypes> however, Python does not notice changes to `$LD_LIBRARY_PATH` at runtime. This means adding DLL directories to `$LD_LIBRARY_PATH` via `os.environ` does not work.

To give an example:

```toml
[tool.poe.tasks]
# Fails to load CUDA DLLs
cmd_based.cmd = "python app.py"
cmd_based.env = { LD_LIBRARY_PATH = "~/code/cuda/lib" }

# successfully loads CUDA DLLs
shell_based.shell = "LD_LIBRARY_PATH=~/code/cuda/lib python app.py"
```

While a workaround would be to use shell tasks in such cases, in my use case, `app.py` accepts an arbitrary number of positional arguments for configuration (e.g. `python app.py foo.a=1 bar.b=2 ...`). However, based on #17, I don't think there is a way to specify an arbitrary number of positional arguments for a shell task? Hence, how would I go about solving this issue?
