### ISSUE TITLE
Support passing sequences to poetry_hooks

### ISSUE THREAD

**Issue by Gobot1234** [nat-n/poethepoet#74]
I'd expect poetry hooks to support sequences as task lists for commands like pre_build etc.

Currently passing a sequence of tasks raises an error:
```py
% poetry build
'Array' object has no attribute 'read'
```
```toml
[tool.poe.poetry_hooks]
pre_build = ["add-cms", "fmt"]
```
Ideally this would run both add cms and fmt when poetry build is ran

**Comment by nat-n** [comment]
Hi @Gobot1234,

This is already achievable by declaring a sequence task then referencing it from the hook. For example

```toml
[tool.poe.poetry_hooks]
pre_build = "_pre_build"

[tool.poe.tasks]
_pre_build = ["add-cms", "fmt"]
```

What do you think of that?

I see how making the hook config work like declaring a sequence task (or any task?) might be convenient, but it could also be confusing as a special case. Does it actually create a sequence task – which actually consists of declaring inline tasks – or just behave a bit like one but in a more limited way? For completeness should it be possible to declare any kind of task directly as a hook? If it just behave a bit like a sequence task without being one then how much of the sequence task logic should be duplicated for this feature?

So I'm unsure exactly what the most elegant enhancement would be here, and whether it's worth the potential complexity, given that it doesn't add much in the way of new capability.
